---
title: "GSE128387"
author: "Jack Karbowski"
date: "6/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GEOquery)
library(tidyverse)
library(BiocManager)
library(limma)
library(stringr)
library(pheatmap)
library(fgsea)
library(data.table)
source("read_cpdb_tab.R")

```

```{r}
gse128<- getGEO("GSE128387")

gse128


#downloading micro array data from omnibus
```


```{r}
head((featureData(gse128[[1]])))


View((featureData(gse128[[1]])))

```


```{r}
length(gse128)

gse128<- gse128[[1]]

#save gse128 as expression set 
```

```{r}
pData(gse128) #sample info 
exprs(gse128) [1,] #gene expression info
```



```{r}
pData(gse128)$data_processing[1]

summary(exprs(gse128)) 

#check how data was processed
#seems like data was proccesed, make a plot below to visualize this 
```


```{r}
#check the log transformed data, summary and visualization 

summary(exprs(gse128))

boxplot(exprs(gse128))
```


```{r}
sampledata<- pData(gse128) #save pData into data frame

view(sampledata)
```


```{r}
sampledata$Pair<- case_when(sampledata$title == "Sample of patient 2, basal sample"~ 2, 
 sampledata$title == "Sample of patient 2, sample al 8 weeks"~ 2, 
 
 sampledata$title == "Sample of patient 3, basal sample"~ 3,
 sampledata$title == "Sample of patient 3, sample al 8 weeks"~ 3, 
 
 sampledata$title == "Sample of patient 5, basal sample"~ 5, 
 sampledata$title == "Sample of patient 5, sample al 8 weeks"~ 5, 
 
 sampledata$title == "Sample of patient 6, basal sample"~ 6,
 sampledata$title == "Sample of patient 6, sample al 8 weeks"~ 6, 
 
 sampledata$title == "Sample of patient 7, basal sample"~ 7, 
 sampledata$title == "Sample of patient 7, sample al 8 weeks"~ 7, 
 
 sampledata$title == "Sample of patient 8, basal sample"~ 8, 
 sampledata$title == "Sample of patient 8, sample al 8 weeks"~ 8, 
 
 sampledata$title == "Sample of patient 9, sample al 8 weeks"~ 9, 
 sampledata$title == "Sample of patient 9, basal sample"~ 9, 
 
 sampledata$title == "Sample of patient 10, basal sample"~ 10, 
 sampledata$title == "Sample of patient 10, sample al 8 weeks"~ 10, 
 
 sampledata$title == "Sample of patient 11, basal sample"~ 11, 
 sampledata$title == "Sample of patient 11, sample al 8 weeks"~ 11, 
 
 sampledata$title == "Sample of patient 13, basal sample"~ 13, 
 sampledata$title == "Sample of patient 13, sample al 8 weeks"~ 13, 
 
 sampledata$title == "Sample of patient 14, basal sample"~ 14, 
 sampledata$title == "Sample of patient 14, sample al 8 weeks"~ 14, 
 
 sampledata$title == "Sample of patient 15, basal sample"~ 15, 
 sampledata$title == "Sample of patient 15, sample al 8 weeks"~ 15, 
 
 sampledata$title == "Sample of patient 16, basal sample"~ 16, 
 sampledata$title == "Sample of patient 16, sample al 8 weeks"~ 16, 
 
 sampledata$title == "Sample of patient 17, basal sample"~ 17, 
 sampledata$title == "Sample of patient 17, sample al 8 weeks"~ 17, 
 
 sampledata$title == "Sample of patient 18, basal sample"~ 18, 
 sampledata$title == "Sample of patient 18, sample al 8 weeks"~ 18, 
 
 sampledata$title == "Sample of patient 19, basal sample"~ 19, 
 sampledata$title == "Sample of patient 19, sample al 8 weeks"~ 19, 
 
 sampledata$title == "Sample of patient 20, basal sample"~ 20, 
 sampledata$title == "Sample of patient 20, sample al 8 weeks"~ 20 ,
 
 sampledata$title == "Sample of patient 12, basal sample"~ 12, 
 sampledata$title == "Sample of patient 12, sample al 8 weeks"~ 12, 
 
 sampledata$title == "Sample of patient 4, basal sample"~ 4)




```


```{r}
sampledata$Treatment_Time<- case_when(sampledata$title == "Sample of patient 2, basal sample"~ "inital", 

sampledata$title == "Sample of patient 3, basal sample"~ "inital", 

sampledata$title == "Sample of patient 4, basal sample"~ "inital", 

sampledata$title == "Sample of patient 5, basal sample"~ "inital", 

sampledata$title == "Sample of patient 6, basal sample"~ "inital", 

sampledata$title == "Sample of patient 7, basal sample"~ "inital", 

sampledata$title == "Sample of patient 8, basal sample"~ "inital",

sampledata$title == "Sample of patient 9, basal sample"~ "inital", 

sampledata$title == "Sample of patient 10, basal sample"~ "inital", 

sampledata$title == "Sample of patient 11, basal sample"~ "inital", 

sampledata$title == "Sample of patient 12, basal sample"~ "inital", 

sampledata$title == "Sample of patient 13, basal sample"~ "inital", 

sampledata$title == "Sample of patient 14, basal sample"~ "inital", 

sampledata$title == "Sample of patient 15, basal sample"~ "inital", 

sampledata$title == "Sample of patient 16, basal sample"~ "inital", 

sampledata$title == "Sample of patient 17, basal sample"~ "inital",

sampledata$title == "Sample of patient 18, basal sample"~ "inital",

sampledata$title == "Sample of patient 19, basal sample"~ "inital",

sampledata$title == "Sample of patient 20, basal sample"~ "inital", 

sampledata$title == "Sample of patient 2, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 3, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 4, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 5, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 6, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 7, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 8, sample al 8 weeks"~ "8 Weeks",

sampledata$title == "Sample of patient 9, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 10, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 11, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 12, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 13, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 14, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 15, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 16, sample al 8 weeks"~ "8 Weeks", 

sampledata$title == "Sample of patient 17, sample al 8 weeks"~ "8 Weeks",

sampledata$title == "Sample of patient 18, sample al 8 weeks"~ "8 Weeks",

sampledata$title == "Sample of patient 19, sample al 8 weeks"~ "8 Weeks",

sampledata$title == "Sample of patient 20, sample al 8 weeks"~ "8 Weeks")

```

```{r}
sampledata<- dplyr::select(sampledata,  title , Pair, Treatment_Time)

sampledata
#selecting columns that we need for analysis 
#try Gsub 
```

```{r}
Pair <- factor(sampledata$Pair)

Treatment_Time<- factor(sampledata$Treatment_Time)

design_128<- model.matrix( ~Pair +Treatment_Time)

design_128
```

```{r}
fit128<- lmFit(gse128, design_128)

head(fit128$coefficients)

fit128_2 <- eBayes(fit128)

saveRDS(fit128_2,file = "../FLX_datasets/GSE128387/DE_GSE128387.rds")

topTable(fit128_2)
topTable1 <- topTable(fit128_2, coef="Treatment_Timeinital",number = 20)

summary(decideTests(fit128_2))
table(decideTests(fit128_2))

topTable1
#NUMBER TOPTABLE 

```

GSE ANALYSIS

```{r}
fit128_2=readRDS("../FLX_datasets/GSE128387/DE_GSE128387.rds")

topTable1 <- topTable(fit128_2, coef="Treatment_Timeinital",number = Inf)
#topTable1$GeneSymbol <- mapIds(org.Hs.eg.db, keys=topTable1gse128_fdata@data$SPOT_ID , column="SYMBOL", keytype="ENSEMBLTRANS")
topTable1$GeneSymbol = gsub(" //.*","",gsub("^([^/]+)// ","",topTable1$gene_assignment))

topTable1=topTable1 %>% 
  arrange(desc(AveExpr)) %>%
  filter(GeneSymbol!="---") %>%
  filter(!duplicated(GeneSymbol))

stat=topTable1$t
names(stat)=topTable1$GeneSymbol

CPDBpaths=read_cpdb_tab("CPDB_pathways_genes_symbol.tab")

fgseaRes128 <- fgsea(CPDBpaths, stat, minSize=10)

saveRDS(fgseaRes128,"../FLX_datasets/GSE128387/GSEA_GSE128387.rds")

```

